### ISSUE TITLE
Improve prism language file

### ISSUE THREAD

**Issue by JeanBarriere** [storyscript/www.storyscript.io#71]
We need to improve the prism language file based from our vscode highlighting syntax.

 - [vscode/syntaxes/story.tmLanguage.json](https://github.com/storyscript/vscode/blob/master/syntaxes/story.tmLanguage.json)

Contributions welcomed

**Comment by wilzbach** [comment]
The syntax files comes from here: https://github.com/storyscript/syntax

Maybe we can just switch to a different highlighter that supports  Texmate, Atom, Ace, Pygements, Rouge or Sublime 3?

An choice would be Ace: https://ace.c9.io

Obviously Ace is a lot heavier than Prism.js, but for now using it might be easier than rewriting the Storyscript grammar in yet another format.
